DROP TABLE IF EXISTS users_deals;
DROP TABLE IF EXISTS users_operations;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS deals;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login     varchar(30) UNIQUE NOT NULL,
    password  varchar(30)        NOT NULL,
    email     varchar UNIQUE     NOT NULL,
    name      varchar,
    surname   varchar,
    nickname  varchar,
    date_time timestamp          NOT NULL,
    balance   integer DEFAULT 0
);


CREATE TABLE deals
(
    id                          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                        varchar(30) NOT NULL,
    date_time                   timestamp   NOT NULL,
    status                      varchar     NOT NULL,
    sum                         integer     NOT NULL,
    currency                    integer     NOT NULL,
    date_time_of_last_operation timestamp


);

CREATE TABLE operations
(
    id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deal_id   integer REFERENCES deals (id),
    name      varchar(30) NOT NULL,
    date_time timestamp   NOT NULL,
    status    varchar     NOT NULL,
    sum       integer     NOT NULL,
    currency  integer     NOT NULL

);

CREATE TABLE users_deals
(
    user_id     integer REFERENCES users (id),
    deal_id     integer REFERENCES deals (id),
    approvement varchar NOT NULL,
    balance     integer DEFAULT 0,
    PRIMARY KEY (user_id, deal_id)
);



CREATE TABLE users_operations
(
    user_id                  integer REFERENCES users (id),
    operation_id             integer REFERENCES operations (id),
    status                   varchar NOT NULL DEFAULT 'OPEN',
    approvement              varchar NOT NULL DEFAULT 'NOT_APPROVE',
    contribution_debt_reduce varchar,
    PRIMARY KEY (user_id, operation_id)
);

CREATE TABLE contacts
(
    user_id    integer REFERENCES users (id),
    contact_id integer REFERENCES users (id)
);


-- POPULATION


INSERT INTO users(login, password, email, name, surname, nickname, date_time)
VALUES ('kema', 'hooinKema9', 'hooinkema@gmail.com', 'Okabe', 'Rintaro', 'Hooin Kema', '2022-10-19 10:23:54');
INSERT INTO users(login, password, email, name, surname, nickname, date_time)
VALUES ('kurisu', 'kristina', 'kurisu@gmail.com', 'Kurisu', 'Makise', 'Zombie', '2022-10-15 13:30:00');
INSERT INTO users(login, password, email, name, surname, nickname, date_time)
VALUES ('mauri', 'shinamauri', 'maushi@gmail.com', 'Mauri', 'Shina', 'Maushi', '2022-10-22 17:00:00');
INSERT INTO users(login, password, email, name, surname, nickname, date_time)
VALUES ('johntitor', 'johntiter', 'johntitor@gmail.com', 'Suzuha', 'Amane', 'Sis Suzu', '1999-05-22 15:00:00');



INSERT INTO deals(name, date_time, status, sum, currency, date_time_of_last_operation)
VALUES ('restaurants', '2022-10-19 10:23:54', 'OPEN', 300, 840, '2022-10-19 10:23:54');
INSERT INTO deals(name, date_time, status, sum, currency, date_time_of_last_operation)
VALUES ('gadget lab', '2009-07-19 10:00:0', 'OPEN', 1000, 840, '2009-09-19 10:00:0');



INSERT INTO operations(name, deal_id, date_time, status, sum, currency)
VALUES ('Nyan Nyan', 1, '2022-10-19 10:23:54', 'OPEN', 300, 840);
INSERT INTO operations(name, deal_id, date_time, status, sum, currency)
VALUES ('Bananas', 2, '2009-07-19 10:00:0', 'OPEN', 400, 840);
INSERT INTO operations(name, deal_id, date_time, status, sum, currency)
VALUES ('IBN 5100', 2, '2009-09-19 10:00:0', 'OPEN', 600, 840);


INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (1, 1, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (2, 1, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (3, 1, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (1, 2, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (2, 2, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (3, 2, 'APPROVE');
INSERT INTO users_deals(user_id, deal_id, approvement)
VALUES (4, 2, 'APPROVE');



INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (2, 1, '300.0|0.0|0.0');
INSERT INTO users_operations(user_id, operation_id)
VALUES (1, 1);
INSERT INTO users_operations(user_id, operation_id)
VALUES (3, 1);

INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (3, 2, '400.0|0.0|0.0');
INSERT INTO users_operations(user_id, operation_id)
VALUES (2, 2);
INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (1, 2, '0.0|0.0|100.0');


INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (1, 3, '400.0|0.0|0.0');
INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (4, 3, '200.0|0.0|0.0');
INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (2, 3, '0.0|100.0|0.0');
INSERT INTO users_operations(user_id, operation_id, contribution_debt_reduce)
VALUES (3, 3, '0.0|0.0|100.0');

INSERT INTO contacts
VALUES (1, 2);
INSERT INTO contacts
VALUES (1, 3);
INSERT INTO contacts
VALUES (1, 4);
INSERT INTO contacts
VALUES (2, 3);
INSERT INTO contacts
VALUES (2, 4);
INSERT INTO contacts
VALUES (3, 4);